---
 - hosts: all
   become: yes
   tasks:
     - name: install a webserver
       yum:
        name: httpd
        state: latest
       when: ansible_distibution = 'RedHat'
     - name: start the service
       service:
         name:httpd
         start: started
